### ISSUE TITLE
Filtering by GM2MField values

### ISSUE THREAD

**Issue by tkhyn** [tkhyn/django-gm2m#31]
**[Original report](https://bitbucket.org/tkhyn/django-gm2m/issue/31) by Nick Guziy (Bitbucket: [Nick Guzy](https://bitbucket.org/Nick Guzy), ).**

----------------------------------------

Hi Thomas! I can't figure out if I can filter model with GM2MField by its value, like I can do with django's GenericForeignKey.

Here is my case:

```
#!python

class Option(models.Model):
   ....

class Main(models.Model):
    options = GM2MField()

option = Option.objects.create()
```
what I want to achieve is to get all instances of Main model, that have option in the options GM2MField i.e.

```
#!python

Main.objects.filter(options=option)
```
this code raises Exception

```
#!python

FieldError: Field 'options' does not generate an automatic reverse relation and therefore cannot be used for reverse querying. If it is a GenericForeignKey, consider adding a GenericRelation.
```
Can you please help me? Should I manually add a relation (from gm2m/relations.py) to Option class or am I making invalid lookup?

**Comment by eriktelepovsky** [comment]
Hello. The following goal:

``mains_with_options = Main.objects.filter(options=[option1, option2])``

can be also achieved this way:

```
option_ct = ContentType.objects.get_for_model(Option)
im = create_gm2m_intermediary_model(getattr(Main, 'options').field, Main)
ids_of_mains_with_options = set(im.objects.filter(gm2m_ct_id=option_ct.id, gm2m_pk__in=[option1.pk, option2.pk]).values_list('gm2m_src_id', flat=True))
mains_with_options = Main.objects.filter(id__in=ids_of_mains_with_options)
```
