### ISSUE TITLE
related_query_name

### ISSUE THREAD

**Issue by tkhyn** [tkhyn/django-gm2m#41]
**[Original report](https://bitbucket.org/tkhyn/django-gm2m/issue/41) by Ben Wilkins (Bitbucket: [benprezola](https://bitbucket.org/benprezola), ).**

----------------------------------------

I am specifying a GM2M field in an abstract class.

As documented here: https://docs.djangoproject.com/en/2.1/topics/db/models/#be-careful-with-related-name-and-related-query-name - I should be able to specify a related_query_name of "%(class)s" however that does not work for `related_query_name`. (It does work for `related_name` though)

**Comment by eriktelepovsky** [comment]
Closing due to no reply.
