### ISSUE TITLE
Migrate repo to GitHub

### ISSUE THREAD

**Issue by tkhyn** [tkhyn/django-gm2m#46]
**[Original report](https://bitbucket.org/tkhyn/django-gm2m/issue/46) by Michael Hays (Bitbucket: [michaelhays](https://bitbucket.org/michaelhays), GitHub: [michaelhays](https://github.com/michaelhays)).**

----------------------------------------

Hey Thomas, thanks a bunch for this tool. I saw from [this comment](https://bitbucket.org/tkhyn/django-gm2m/issues/45/makemigrations-gm2mfield-exception-when#comment-52698721) that you are no longer able to continue working on django-gm2m. I’d suggest moving this to GitHub, as I think more people would contribute, and there would be a better chance that someone else would be able to take over maintenance duties.

‌

It’s really easy to do: [https://help.github.com/en/articles/importing-a-repository-with-github-importer](https://help.github.com/en/articles/importing-a-repository-with-github-importer)

**Comment by michaelhays** [comment]
Awesome! Thanks a bunch :)
