### ISSUE TITLE
Is "django-gm2m" still maintained?

### ISSUE THREAD

**Issue by martinzugnoni** [tkhyn/django-gm2m#48]
Hello @tkhyn. First of all, thanks for the great work at `django-gm2m`.

I'm planning to use it in a personal project and checking the release logs in PyPi I saw that the last release was published on Apr 16, 2018 - long time ago.

I also saw though, that this Github repo is kind of new (migrated from the old Bitbucket repo) and that you guys added some commits in mid 2019.

What are the plans about this project? Is it still under maintenance by you or anybody else?

Thank you in advance.

**Comment by tkhyn** [comment]
Hi,
As per some of my previous comments, I am no longer using django-gm2m and have no time to do anything to it. I am not aware of anybody willing to step in as a maintainer, although the move to github was motivated by a user who seemed to want to contribute. I will happily accept any PR to solve one of the few minor issues and/or feature requests.
