### ISSUE TITLE
deprecated dependeny:six 

### ISSUE THREAD

**Issue by k34n4y138** [tkhyn/django-gm2m#49]
the package depends on six, assumed to be found in django.utils as the import statement is:
`from django.utils import six`
six is  [no longer to be found in django.utils](https://github.com/divio/django-classy-tags/issues/48)
the import statement: `from django.utils import six`
must be changed to : 'import six'
and the  package six must be added to the requirements as a third party package
the change of the statement must be applied to the following file:

-  fileds.py: [line 3]
-  relations.py: [line 9]
-  helpers.py: [line 5]
- query.py: [line 4]
- deletion.py: [line 3]

edit: I've forked and edited the repo as listed above, you can download and replace the old one by:
` pip install -e git+https://github.com/k34n4y138/django-gm2m.git@develop#egg=django-gm2m --upgrade`

**Comment by ChillarAnand** [comment]
@tkhyn Any plans for supporting Django 3.0?

**Comment by tkhyn** [comment]
Fixed in 55d205ec thanks to @devbis
