### ISSUE TITLE
Pypi version 1.1

### ISSUE THREAD

**Issue by tomasgarzon** [tkhyn/django-gm2m#53]
Hi, I see that you have a new version in master (1.1a) but it's not available on Pypi yet. I'm working on a project, and start migrating to Django 3.1 last weeks but I can't create new migration because of a bug fixed in your new version.

**Comment by tkhyn** [comment]
Hi, I'll push a release soon but in the mean time you can `pip install git+https://github.com/tkhyn/django-gm2m.git@develop`

**Comment by tkhyn** [comment]
finally did it now, v1.1.1 is available on pypi

**Comment by tomasgarzon** [comment]
thanks a lot!
