### ISSUE TITLE
Django 4.0 incompatibility due to deprecated function

### ISSUE THREAD

**Issue by stoffi92** [tkhyn/django-gm2m#56]
As of https://docs.djangoproject.com/en/4.0/releases/3.0/#deprecated-features-3-0 `django.utils.encoding.force_text()` has been deprecated with django 3.0 and with django 4.0 has been removed from the django.

A quick search in the repo gives two occurrences of force_text which are incompatible with django-4.0: 

- gm2m/serializers/python.py 
- gm2m/fields.py

Cheers Christoph

**Comment by kojibhy** [comment]
looks like this project not develop any more.

**Comment by jvacek** [comment]
There's an open PR #55 for this, and a large amount of the forks seem to have it implemented. @tkhyn any chance to take a look at this? Was looking at using this package but I might avoid it if I know I'll have to remove it next time I upgrade Django.

**Comment by tkhyn** [comment]
Hi

Sorry for popping up a bit late. For some reason I did not get any email notifications about this issue nor the linked PR and just got @jvacek's last reply.

I will merge the PR in the develop branch, but will not push a new release as deeper changes - that I am not prepared to do - are required to make django-gm2m compatible with Django 3.2+.
