### ISSUE TITLE
Incompatibility with Django > 3.1

### ISSUE THREAD

**Issue by tkhyn** [tkhyn/django-gm2m#57]
Dear django-gm2m users,

I have not used Django for about 4 years, and have basically no free time to carry on developing this Django app. It relies heavily on private APIs that keep changing and I cannot afford spending (a lot of) time fixing it each time Django changes. My hope was that this app would be useful enough to be merged into Django trunk one day to avoid having to rebuild it at each new release, but it hasn't happened and probably never will.

The current version works with Django 3.1, is broken with Django 3.2 and even more broken with Django 4.0 - try running the test suite!

I am very unlikely to have the time to dive into Django's internals again and make django-gm2m compatible with Django 3.2+. If anyone is keen to take over, I have just pushed a few housekeeping commits on the develop branch (moving to pytest, updating versions, etc.) that will make it a bit easier to start for anyone interested.

I will happily transfer / share the rights to upload to pypi to the new maintainer(s).

**Comment by eriktelepovsky** [comment]
Solved by PR #62
