### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by eriktelepovsky** [tkhyn/django-gm2m#63]
@tkhyn do you plan to continue working on this app? If not, can you make me the maintainer please?

**Comment by tkhyn** [comment]
Ahoj, no I don't plan to keep maintaining this app as per #57. Thanks for reaching out, I have sent you an invite so you can become a maintainer.

**Comment by eriktelepovsky** [comment]
Thank you. Invitation accepted. Can you also change the maintainer of the PyPi project?

https://pypi.org/project/django-gm2m

My username on pypi is pragmaticmates.com

**Comment by tkhyn** [comment]
Done!
